# Generated by Django 5.2.8 on 2025-11-26 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], default='M', max_length=1),
        ),
    ]
