# Generated by Django 5.2.8 on 2025-11-27 09:48

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComuneArpa',
            fields=[
                ('codice_istat', models.CharField(db_column='esri_geodatabase.geoportale.lim_01_comuni_in_vigore.comune_ist', max_length=50, primary_key=True, serialize=False, verbose_name='Codice ISTAT')),
                ('nome', models.CharField(db_column='esri_geodatabase.geoportale.lim_01_comuni_in_vigore.comune_nom', max_length=255, verbose_name='Comune')),
                ('provincia', models.CharField(db_column='esri_geodatabase.geoportale.lim_01_comuni_in_vigore.provin_nom', max_length=255, verbose_name='Provincia')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(db_column='geom', srid=4326, verbose_name='Confini Amministrativi')),
            ],
            options={
                'verbose_name': 'Comune ARPA',
                'verbose_name_plural': 'Comuni ARPA',
                'db_table': 'medie_radon_comunali',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
    ]
