# Generated by Django 5.2.8 on 2025-12-03 14:53

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('territorio', '0002_create_comuni_completi_view'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaPrioritariaRadon',
            fields=[
                ('codice_istat', models.CharField(db_column='esri_geodatabase.geoportale.lim_01_comuni_in_vigore.comune_ist', max_length=50, primary_key=True, serialize=False, verbose_name='Codice ISTAT')),
                ('nome', models.CharField(db_column='esri_geodatabase.geoportale.lim_01_comuni_in_vigore.comune_nom', max_length=255, verbose_name='Comune')),
                ('provincia', models.CharField(db_column='esri_geodatabase.geoportale.lim_01_comuni_in_vigore.provin_nom', max_length=255, verbose_name='Provincia')),
                ('area_prioritaria', models.CharField(db_column='esri_geodatabase.geoportale.rad_18_tab_comuni_radon.ap', help_text='Indica se il comune è in area prioritaria secondo il Piano Radon', max_length=10, verbose_name='Area Prioritaria')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(db_column='geom', srid=4326, verbose_name='Confini Amministrativi')),
            ],
            options={
                'verbose_name': 'Area Prioritaria Radon',
                'verbose_name_plural': 'Aree Prioritarie Radon',
                'db_table': 'aree_prioritarie_radon',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ComuneCompleto',
            fields=[
                ('codice_istat', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Codice ISTAT')),
                ('nome', models.CharField(max_length=255, verbose_name='Comune')),
                ('provincia', models.CharField(max_length=255, verbose_name='Provincia')),
                ('media_radon', models.FloatField(blank=True, null=True, verbose_name='Concentrazione Media Radon (Bq/m³)')),
                ('area_prioritaria', models.CharField(blank=True, max_length=255, null=True, verbose_name='Area Prioritaria Piano Radon')),
                ('unita_litologica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Unità Litologica')),
                ('litologia', models.CharField(blank=True, max_length=100, null=True, verbose_name='Litologia')),
                ('eta_geologica', models.CharField(blank=True, max_length=40, null=True, verbose_name='Età Geologica')),
                ('descrizione_geologica', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descrizione Geologica')),
                ('dominio_geologico', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dominio Geologico')),
                ('classe_permeabilita', models.IntegerField(blank=True, help_text='1=Alta, 2=Media, 3=Bassa, 4=Molto Bassa', null=True, verbose_name='Classe Permeabilità')),
                ('distanza_faglia_m', models.FloatField(blank=True, null=True, verbose_name='Distanza dalla Faglia più vicina (m)')),
                ('tipo_faglia_vicina', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tipo Faglia più vicina')),
                ('geom', django.contrib.gis.db.models.fields.PolygonField(srid=4326, verbose_name='Confini Amministrativi')),
            ],
            options={
                'verbose_name': 'Comune Completo',
                'verbose_name_plural': 'Comuni Completi',
                'db_table': 'comuni_completi',
                'ordering': ['nome'],
                'managed': False,
            },
        ),
    ]
